// ─── Translations & Static Constants ─────────────────────────────────────────

export const T = {
  en: {
    appName: "STEELPOS", appSub: "Management System",
    dashboard: "Dashboard", inventory: "Inventory", products: "Products",
    purchase: "Purchase", sales: "Sales", staff: "Staff", billing: "Billing & Invoice",
    accounts: "Accounts",
    ledger: "Payable & Receivable",
    logout: "Logout", login: "Login", email: "Email", password: "Password",
    welcomeBack: "Welcome Back",
    authenticating: "Authenticating...", loading: "Loading...",
    save: "Save", saving: "Saving...", cancel: "Cancel", close: "Close",
    add: "Add", edit: "Edit", delete: "Delete", update: "Update",
    search: "Search products...", allCategories: "All Categories",
    totalProducts: "Total Products", inventoryValue: "Inventory Value",
    lowStockItems: "Low Stock Items", outOfStock: "Out of Stock",
    inStock: "In Stock", lowStock: "Low Stock",
    adjustStock: "Adjust Stock", currentStock: "Current Stock",
    addStock: "+ Add Stock", removeStock: "− Remove Stock",
    applyAdjustment: "Apply Adjustment", adjust: "Adjust",
    category: "Category", pipe: "Pipe", chader: "Chader",
    net: "Net", hardware: "Hardware", custom: "Custom Product",
    pipeDetails: "Pipe Details",
    gauge: "Gauge", unit: "Unit", length: "Length (optional)",
    weightPerPiece: "Weight/piece kg (optional)",
    productName: "Product Name (auto-generated, editable)",
    nameHint: "Select inches & gauge above — name builds automatically",
    percentagePricing: "Percentage Pricing (optional)",
    basePrice: "Base Price (PKR)", percentage: "% (e.g. -17.50)",
    applyPercent: "Apply %",
    pricePerPipe: "Price per Pipe (PKR)",
    pricePerPipeHint: "Set 1 pipe ka rate — quantity se total auto-banega",
    finalPrice: "Final Price per unit (PKR)",
    finalRate: "Final Rate",
    quantityCalc: "Quantity Calculator",
    numberOfPipes: "Number of Pipes",
    priceFor: "Price for", pipes: "pipes",
    chaderType: "Chader Type", productNameLabel: "Product Name",
    openingStock: "Opening Stock", pricePerUnit: "Price per unit (PKR)",
    rate: "Rate",
    addProduct: "Add Product", addHardwareProduct: "Add Hardware Product", editProduct: "Edit Product", saveProduct: "Save Product",
    updateProduct: "Update Product", deleteConfirm: "Delete",
    totalSpent: "Total Spent", totalOrders: "Total Orders",
    supplier: "Supplier Name", selectProduct: "Select Product",
    invoiceNum: "Invoice #", date: "Date", quantity: "Quantity",
    ratePKR: "Rate (PKR)", totalAmount: "Total Amount",
    addPurchase: "Add Purchase", editPurchase: "Edit Purchase",
    totalRevenue: "Total Revenue", totalInvoices: "Total Invoices",
    customer: "Customer Name", addSale: "New Sale", editSale: "Edit Sale",
    invoiceTotal: "Invoice Total", availableStock: "Available",
    staffMembers: "staff members", addStaff: "Add Staff", editStaff: "Edit Staff",
    fullName: "Full Name", emailAddress: "Email Address",
    createStaff: "Create Staff", updateStaff: "Update Staff",
    administrator: "Administrator", staffRole: "Staff",
    todayRevenue: "Today's Revenue", myTotalSales: "Total My Sales",
    productsInStock: "Products In Stock", billingCounter: "Billing Counter",
    newSaleInvoice: "New Sale / Invoice", newSale: "New Sale — Create Invoice",
    saleReturn: "Sale Return", purchaseReturn: "Purchase Return",
    returnRecords: "Return records",
    saveCreateInvoice: "Save & Create Invoice", saleRate: "Sale Rate (PKR)",
    recentSales: "Recent Sales", recentProducts: "Recent Products",
    noSalesYet: "No sales yet", noProductsYet: "No products yet",
    netProfit: "Net Profit", profitable: "Profitable", loss: "Loss",
    transactions: "transactions", orders: "orders",
    inventoryItems: "Inventory Items", purchaseManagement: "Purchase Management",
    salesManagement: "Sales Management", staffManagement: "Staff Management",
    purchaseRecords: "purchase records", salesRecords: "sales records",
    noRecords: "No records found", noProductsFound: "No products found",
    actions: "Actions", number: "#", name: "Name", size: "Size / Type",
    stock: "Stock", status: "Status", priceUnit: "Price/Unit",
    currentStockLabel: "Current Stock",
    lowStockAlert: "Low Stock:",
    staffCreated: "Staff member created!",
    saleRecorded: "Sale recorded!",
    passwordHint: "(Leave empty to keep same)",
    passwordCreate: "Create a strong password",
    todayInvoices: "invoices today", totalLabel: "Total",
    all: "All",
    deleteProductConfirm: "Delete this product?",
    deletePurchaseConfirm: "Delete this purchase?",
    deleteSaleConfirm: "Delete this sale?",
    deleteStaffConfirm: "Remove this staff member?",
    serverError: "Cannot connect to server. Is backend running?",
    wrongCredentials: "Incorrect email or password",
    percentOptional: "(optional)",
    productType: "Product Type",
    selectType: "Select Type",
    pipeType: "Pipe Type", roundPipe: "Round Pipe", squarePipe: "Square Pipe",
    subType: "Sub Type", soft: "Soft", hard: "Hard", inches: "Inches",
    addRow: "+ Add Row",
    purchasePrice: "Purchase Price (PKR)",
    salePrice: "Sale Price (PKR)",
    weight: "Weight (kg)",
    feet: "Feet",
    purchasePricePerFt: "Purchase Price/Ft",
    salePricePerFt: "Sale Price/Ft",
    qty: "Qty",
    purchasePricePerPc: "Purchase Price/Pc",
    salePricePerPc: "Sale Price/Pc",
    totalPurchase: "Total Purchase",
    savePurchase: "Save Purchase",
    addEntryRow: "Add Entry Row",
    startEntry: 'Click "Add Row" to start entering data',
    accountsManagement: "Accounts Management",
    ledgerManagement: "Payable & Receivable",
    addAccount: "Add Account",
    editAccount: "Edit Account",
    accountName: "Account Name",
    accountType: "Account Type",
    bankAccount: "Bank Account",
    cashAccount: "Cash Account",
    bankName: "Bank Name",
    accountNumber: "Account Number (optional)",
    openingBalance: "Opening Balance (PKR)",
    currentBalance: "Current Balance",
    totalBanks: "Total Banks",
    totalCash: "Total Cash",
    totalBalance: "Total Balance",
    noAccountsYet: "No accounts added yet",
    deleteAccountConfirm: "Delete this account?",
    accountAdded: "Account added successfully!",
    selectBank: "Select Bank",
    customBank: "Other / Custom",
    accountsPage: "Accounts",
    price: "Price",
    grandTotal: "Grand Total",
    pipeProduct: "Pipe / Product",
    type: "Type",
    searchPlaceholder: "Search by name, size, gauge...",
    pricePerFeet: "Price per Feet (PKR)",
    selectProductEntry: "Select a product to add entries",
    addProductBlock: "+ Add Product",
  },
  ur: {
    appName: "اسٹیل پی او ایس", appSub: "مینجمنٹ سسٹم",
    dashboard: "ڈیش بورڈ", inventory: "انوینٹری", products: "مصنوعات",
    purchase: "خریداری", sales: "فروخت", staff: "عملہ", billing: "بلنگ",
    accounts: "اکاؤنٹس",
    ledger: "ادائیگی و وصولی",
    logout: "لاگ آؤٹ", login: "لاگ ان", email: "ای میل", password: "پاس ورڈ",
    welcomeBack: "خوش آمدید",
    authenticating: "تصدیق ہو رہی ہے...", loading: "لوڈ ہو رہا ہے...",
    save: "محفوظ کریں", saving: "محفوظ ہو رہا ہے...", cancel: "منسوخ", close: "بند کریں",
    add: "شامل کریں", edit: "ترمیم", delete: "حذف", update: "اپڈیٹ",
    search: "مصنوعات تلاش کریں...", allCategories: "تمام اقسام",
    totalProducts: "کل مصنوعات", inventoryValue: "انوینٹری کی مالیت",
    lowStockItems: "کم اسٹاک اشیاء", outOfStock: "اسٹاک ختم",
    inStock: "اسٹاک موجود", lowStock: "کم اسٹاک",
    adjustStock: "اسٹاک درست کریں", currentStock: "موجودہ اسٹاک",
    addStock: "+ اسٹاک بڑھائیں", removeStock: "− اسٹاک کم کریں",
    applyAdjustment: "تبدیلی لگائیں", adjust: "درست کریں",
    category: "قسم", pipe: "پائپ", chader: "چادر",
    net: "جالی", hardware: "ہارڈ ویئر", custom: "کسٹم مصنوع",
    pipeDetails: "پائپ کی تفصیل",
    gauge: "گیج", unit: "اکائی", length: "لمبائی (اختیاری)",
    weightPerPiece: "وزن/ٹکڑا کلو (اختیاری)",
    productName: "مصنوع کا نام (خودکار، قابل ترمیم)",
    nameHint: "اوپر انچ اور گیج منتخب کریں — نام خودبخود بنے گا",
    percentagePricing: "فیصد قیمت (اختیاری)",
    basePrice: "بنیادی قیمت (PKR)", percentage: "فیصد (مثلاً -17.50)",
    applyPercent: "فیصد لگائیں",
    pricePerPipe: "ایک پائپ کی قیمت (PKR)",
    pricePerPipeHint: "ایک پائپ کا ریٹ لکھیں",
    finalPrice: "فی اکائی آخری قیمت (PKR)",
    finalRate: "آخری ریٹ",
    quantityCalc: "مقدار کیلکولیٹر",
    numberOfPipes: "پائپوں کی تعداد",
    priceFor: "قیمت", pipes: "پائپ",
    chaderType: "چادر کی قسم", productNameLabel: "مصنوع کا نام",
    openingStock: "ابتدائی اسٹاک", pricePerUnit: "فی اکائی قیمت (PKR)",
    rate: "ریٹ",
    addProduct: "مصنوع شامل کریں", addHardwareProduct: "ہارڈ ویئر آئٹم شامل کریں", editProduct: "مصنوع ترمیم کریں", saveProduct: "مصنوع محفوظ کریں",
    updateProduct: "مصنوع اپڈیٹ کریں", deleteConfirm: "حذف کریں",
    totalSpent: "کل خرچ", totalOrders: "کل آرڈر",
    supplier: "سپلائر کا نام", selectProduct: "مصنوع منتخب کریں",
    invoiceNum: "انوائس نمبر", date: "تاریخ", quantity: "مقدار",
    ratePKR: "ریٹ (PKR)", totalAmount: "کل رقم",
    addPurchase: "خریداری شامل کریں", editPurchase: "خریداری ترمیم کریں",
    totalRevenue: "کل آمدن", totalInvoices: "کل انوائس",
    customer: "گاہک کا نام", addSale: "نئی فروخت", editSale: "فروخت ترمیم کریں",
    invoiceTotal: "انوائس کی کل رقم", availableStock: "دستیاب اسٹاک",
    staffMembers: "عملے کے اراکین", addStaff: "عملہ شامل کریں", editStaff: "عملہ ترمیم کریں",
    fullName: "پورا نام", emailAddress: "ای میل پتہ",
    createStaff: "عملہ بنائیں", updateStaff: "عملہ اپڈیٹ کریں",
    administrator: "منتظم", staffRole: "عملہ",
    todayRevenue: "آج کی آمدن", myTotalSales: "میری کل فروخت",
    productsInStock: "دستیاب مصنوعات", billingCounter: "بلنگ کاؤنٹر",
    newSaleInvoice: "نئی فروخت / انوائس", newSale: "نئی فروخت — انوائس بنائیں",
    saleReturn: "فروخت واپسی", purchaseReturn: "خریداری واپسی",
    returnRecords: "واپسی کے ریکارڈ",
    saveCreateInvoice: "محفوظ کریں اور انوائس بنائیں", saleRate: "فروخت ریٹ (PKR)",
    recentSales: "حالیہ فروخت", recentProducts: "حالیہ مصنوعات",
    noSalesYet: "ابھی کوئی فروخت نہیں", noProductsYet: "ابھی کوئی مصنوع نہیں",
    netProfit: "خالص منافع", profitable: "نفع میں", loss: "نقصان میں",
    transactions: "لین دین", orders: "آرڈر",
    inventoryItems: "انوینٹری اشیاء", purchaseManagement: "خریداری مینجمنٹ",
    salesManagement: "فروخت مینجمنٹ", staffManagement: "عملہ مینجمنٹ",
    purchaseRecords: "خریداری کے ریکارڈ", salesRecords: "فروخت کے ریکارڈ",
    noRecords: "کوئی ریکارڈ نہیں", noProductsFound: "کوئی مصنوع نہیں ملا",
    actions: "اقدامات", number: "#", name: "نام", size: "سائز / قسم",
    stock: "اسٹاک", status: "حالت", priceUnit: "فی اکائی قیمت",
    currentStockLabel: "موجودہ اسٹاک",
    lowStockAlert: "کم اسٹاک:",
    staffCreated: "عملہ رکن بنا دیا گیا!",
    saleRecorded: "فروخت ریکارڈ ہو گئی!",
    passwordHint: "(خالی چھوڑیں تو پرانا رہے گا)",
    passwordCreate: "مضبوط پاس ورڈ بنائیں",
    todayInvoices: "آج کے انوائس", totalLabel: "کل",
    all: "سب",
    deleteProductConfirm: "کیا یہ مصنوع حذف کریں؟",
    deletePurchaseConfirm: "کیا یہ خریداری حذف کریں؟",
    deleteSaleConfirm: "کیا یہ فروخت حذف کریں؟",
    deleteStaffConfirm: "کیا یہ عملہ رکن ہٹائیں؟",
    serverError: "سرور سے رابطہ نہیں ہو سکا۔",
    wrongCredentials: "ای میل یا پاس ورڈ غلط ہے",
    percentOptional: "(اختیاری)",
    productType: "مصنوع کی قسم",
    selectType: "قسم منتخب کریں",
    pipeType: "پائپ کی قسم", roundPipe: "گول پائپ", squarePipe: "چورس پائپ",
    subType: "ذیلی قسم", soft: "نرم", hard: "سخت", inches: "انچ",
    addRow: "+ قطار شامل کریں",
    purchasePrice: "خریداری قیمت (PKR)",
    salePrice: "فروخت قیمت (PKR)",
    weight: "وزن (کلو)",
    feet: "فٹ",
    purchasePricePerFt: "خریداری قیمت/فٹ",
    salePricePerFt: "فروخت قیمت/فٹ",
    qty: "مقدار",
    purchasePricePerPc: "خریداری قیمت/عدد",
    salePricePerPc: "فروخت قیمت/عدد",
    totalPurchase: "کل خریداری",
    savePurchase: "خریداری محفوظ کریں",
    addEntryRow: "اندراج قطار شامل کریں",
    startEntry: "شروع کرنے کے لیے \"قطار شامل کریں\" دبائیں",
    accountsManagement: "اکاؤنٹس مینجمنٹ",
    ledgerManagement: "ادائیگی و وصولی",
    addAccount: "اکاؤنٹ شامل کریں",
    editAccount: "اکاؤنٹ ترمیم کریں",
    accountName: "اکاؤنٹ کا نام",
    accountType: "اکاؤنٹ کی قسم",
    bankAccount: "بینک اکاؤنٹ",
    cashAccount: "نقد اکاؤنٹ",
    bankName: "بینک کا نام",
    accountNumber: "اکاؤنٹ نمبر (اختیاری)",
    openingBalance: "ابتدائی رقم (PKR)",
    currentBalance: "موجودہ رقم",
    totalBanks: "کل بینک",
    totalCash: "کل نقد",
    totalBalance: "کل رقم",
    noAccountsYet: "ابھی کوئی اکاؤنٹ نہیں",
    deleteAccountConfirm: "کیا یہ اکاؤنٹ حذف کریں؟",
    accountAdded: "اکاؤنٹ شامل ہو گیا!",
    selectBank: "بینک منتخب کریں",
    customBank: "دیگر / کسٹم",
    accountsPage: "اکاؤنٹس",
    price: "قیمت",
    grandTotal: "کل رقم",
    pipeProduct: "پائپ / مصنوع",
    type: "قسم",
    searchPlaceholder: "نام، سائز، گیج سے تلاش کریں...",
    pricePerFeet: "قیمت فی فٹ (PKR)",
    selectProductEntry: "اندراج کے لیے مصنوع منتخب کریں",
    addProductBlock: "+ مصنوع شامل کریں",
  }
};

// ── Pakistan Banks ───────────────────────────────────────────────────────
export const PAKISTAN_BANKS = [
  "HBL (Habib Bank)",
  "MCB Bank",
  "UBL (United Bank)",
  "Allied Bank (ABL)",
  "National Bank (NBP)",
  "Bank Alfalah",
  "Meezan Bank",
  "Askari Bank",
  "Bank Al Habib",
  "Faysal Bank",
  "Standard Chartered",
  "Habib Metropolitan Bank",
  "Silk Bank",
  "JS Bank",
  "Summit Bank",
  "Soneri Bank",
  "First Women Bank",
  "The Bank of Punjab",
  "Zarai Taraqiati Bank (ZTBL)",
  "Industrial Development Bank (IDBP)",
  "Other / Custom",
];

// ── Pipe: inch sizes ─────────────────────────────────────────────────────
export const ROUND_INCHES = [
  "1/2\"", "3/4\"", "1\"", "1.25\"", "1.5\"", "2\"", "2.5\"", "3\"", "4\""
];

export const SQUARE_INCHES = [
  "1/2\"", "3/4\"", "1\"", "1.25\"", "1.5\"", "2\"", "2.5\"", "3\""
];

// ── Pipe: gauges ─────────────────────────────────────────────────────────
export const PIPE_GAUGES = [
  { value: "14", label: "14 Gauge" },
    { value: "15", label: "15 Gauge" },
  { value: "16", label: "16 Gauge" },
  { value: "18", label: "18 Gauge" },
    { value: "19", label: "19 Gauge" },
  { value: "20", label: "20 Gauge" },
    { value: "21", label: "21 Gauge" },
  { value: "22", label: "22 Gauge" },
  { value: "24", label: "24 Gauge" },
];

// ── Chader types ─────────────────────────────────────────────────────────
export const CHADER_TYPES = [
  { key: "Plain",    emoji: "🔲", label: "Plain Chader",    labelUr: "سادہ چادر"    },
  { key: "Corrugated", emoji: "🌊", label: "Corrugated",   labelUr: "لہریا چادر"   },
  { key: "Galvanized", emoji: "✨", label: "Galvanized",   labelUr: "جستی چادر"    },
  { key: "Color",    emoji: "🎨", label: "Color Coated",   labelUr: "رنگین چادر"   },
  { key: "Custom",   emoji: "📦", label: "Custom",         labelUr: "کسٹم چادر"    },
];

// ── Net types ────────────────────────────────────────────────────────────
export const NET_TYPES = [
  { key: "Chorus",  emoji: "🕸️", label: "Chorus Net",  labelUr: "کورس جالی"  },
  { key: "Break",   emoji: "🔗", label: "Break Net",   labelUr: "بریک جالی"  },
  { key: "Barfii",  emoji: "❄️", label: "Barfii Net",  labelUr: "برفی جالی"  },
];

// ── Net Chorus gauges ────────────────────────────────────────────────────
export const NET_CHORUS_GAUGES = ["14", "16", "18", "20", "22", "24"];

// ── safe helper: product name from object or string ──────────────────────
export const safeProductName = (val) => {
  if (!val) return "—";
  if (typeof val === "string") return val;
  if (typeof val === "object") return val.name || "—";
  return "—";
};
export const safeProductCategory = (val) => {
  if (!val) return "";
  if (typeof val === "string") return "";
  if (typeof val === "object") return val.category || "";
  return "";
};

// ── robust display name for any product ──────────────────────────────────
// Net/Chorus products are auto-named ("Chorus 20G") at save time, but if a
// product's `name` ever ends up blank (older data, etc.) this rebuilds it
// from subType + gauge so it always shows a proper name — same as every
// other category — everywhere a product name is rendered (Products page,
// Billing page product picker, invoices).
export const productDisplayName = (p) => {
  if (!p) return "—";
  if (typeof p === "string") return p;
  const nm = (p.name || "").trim();
  if (nm) return nm;
  const cat = (p.category || "").toLowerCase();
  if (cat === "net" && p.subType === "Chorus") return `Chorus ${p.gauge || ""}`.trim();
  return p.subType || p.category || "—";
};

